### ISSUE TITLE
Peso y dimensiones

### ISSUE THREAD

**Issue by brunoletelle** [New-Bytes/download-price-list-windows#4]
Hola! Como están? 
Estoy trabajando con una Tienda Nube (sin integración directa, la única fuente de datos es la lista de precios, el resto es manual) y quería consultarles si es posible agregar a la lista de precios, las dimensiones y peso de los productos como bulto. Es decir, el peso y dimensiones que utiliza el sistema para calcular el costo de envío. (no las dimensiones del producto sin caja, por ejemplo: el alto de una notebook puede ser de 2cm pero la caja es de 10cm)
El problema es que no figura en ningún lado y al hacer dropshipping con Tienda Nube, no es posible mostrar un precio de envío estimado.
Teniendo las dimensiones y peso, podría agregar alguna integración con Andreani por ejemplo, solo para el cálculo de envío. Luego utilizaría el envío interno de ustedes. 
Muchas gracias

**Comment by mercurioctrl** [comment]
Buenas!

Ya agregamos la semana pasada las medidas en tienda nube, fijate si te aparecen y avisarme así cierro el caso.

**Comment by brunoletelle** [comment]
Hola! Ahí lo revisé, está perfecto. Me ahorraron un montón de tiempo!
Muchísimas gracias

**Comment by brunoletelle** [comment]
Hola de nuevo! Ahora que ya utilicé la lista un par de veces, veo que manualmente tengo que asignarle las columnas cada vez que quiero cargar la lista, porque difiere en el nombre que le da Tienda Nube:
Peso (kg)
Alto (cm)
Ancho (cm)
Profundidad (cm)
![imagen](https://github.com/user-attachments/assets/a3b1bb0a-89c2-421a-90f2-fee50e4754af)

**Comment by mercurioctrl** [comment]
osea que el nombre de las columnas deberia incluir la unidad entre parentesis? el "(kg)", etc ?

**Comment by brunoletelle** [comment]
Hola! Perdon por la demora, si deberían ir  con un espacio entre los parentesis! "Profundidad (cm)".
Edite la lista manual y ya no me figura en error, los interpreta automaticamente

**Comment by brunoletelle** [comment]
Ahí quedó perfecto el cambio, ya puedo subir los precios sin asignar manualmente los valores. Muchas gracias!
