### ISSUE TITLE
Productos sin stock

### ISSUE THREAD

**Issue by brunoletelle** [New-Bytes/download-price-list-windows#5]
Hola! Cómo están? Sigo trabajando en la integración manual con Tienda Nube.
Me encontré con un problema de Stock, creí que era por un producto en particular, pero no.
El problema es el siguiente:
Si un producto que ya estaba cargado en la tienda se queda sin stock en New Bytes. Cuando vuelvo a subir la lista, no se actualiza el stock del producto a "0" (cero). Queda con el stock que tenía en la última update.

La lista de precios no pasa productos sin stock. Entonces cuando subo la lista a la tienda, el producto que se quedó sin stock no se actualiza porque no viene incluido en la lista de precios. Y no se elimina, porque no es posible hacerlo desde la carga masiva, al menos en Tienda Nube.

**Comment by mercurioctrl** [comment]
Hicimos un cambio para incluirlos en cero. Fijate si te sirve y comentame para cerrar el caso

**Comment by brunoletelle** [comment]
Hola! Ahí lo probé! Me sirvió, hay un modelo de notebook (por ejemplo) que pasó de 10 a 0 de stock, y me había quedado con 10 en la tienda.

Después hay un artículo en particular, que fué justo con el que tuve problemas que ya no viene en la lista directamente, https://nb.com.ar/procesador-amd-am5-ryzen-7-7800x3d_-_118151

**Comment by mercurioctrl** [comment]
Lo tenes solucionado?

**Comment by brunoletelle** [comment]
Hola! Sisi, volvió a aparecer en la lista. De un momento a otro no aparecía listado. En la pagina de NB aparecía pero sin stock, y ahora esta con full stock.
